### ISSUE TITLE
貌似不支持linux系统

### ISSUE THREAD

**Issue by MeowSprite** [eleveni386/netmonitor#1]
主要由于net_connections下58行的psutil.net_connections()函数并不支持unix类操作系统的socket。不知道有没有其他的解决办法。

**Comment by eleveni386** [comment]
我自己就是Ubuntu, Ubuntu下测试没问题吖, 能给出具体出错信息么

**Comment by MeowSprite** [comment]
我弄错了python-psutil的版本。直接使用软件源安装python-psutil，版本比较低，是1.2的。之前谷歌到有人说net_connections不支持linux，看文档也说不支持Solaris等unix的socket，结果想当然了。pip安装了python-psutil的最新版就好了。建议在readme应该提醒一下,安装python-psutil最新的模块。
![12](https://cloud.githubusercontent.com/assets/7733022/8475353/0ebc7316-20ea-11e5-8ed0-4d40859bf66a.png)
还有运行不长时间就出现上面的错误，我使用捕获异常pass后就没事了。

**Comment by eleveni386** [comment]
好的, 多谢提醒. 不过 这个版本 当前没啥实际意义.. 不懂内核编程. 不然直接让内核告诉我进程的流量 而且还可以限制进程流量 你会嘛?

**Comment by MeowSprite** [comment]
这个我也不会，我正在做一个流量监控项目，现在也是通过libpcap抓取包来分析的，主要参考的iftop这个工具。内核方面的我还不是特别了解。
